### ISSUE TITLE
libpq-dev package required for pq (postgresql) gem

### ISSUE THREAD

**Issue by westonhankins** [RefugeesOnRails/machina#4]
The team in Munich had issues with the script when it failed installing the pq gem. They had to manually apt-get the `libpq-dev` package and then it worked fine.

**Comment by phillipoertel** [comment]
Thanks for adding this. The script itself ran fine, only when trying to bundle a (newly created, empty) rails app which had the pg gem as dependency, we got errors; the gem wouldn't compile. It works with the libpq-dev package installed.

**Comment by Javachic** [comment]
Hi Philip - quick question - did you have problems with any subsequent tasks (downloading images, etc) after running this script? We aren't sure if we ran into this problem due to residual hardware issues or if we did something incorrectly.

**Comment by phillipoertel** [comment]
You mean problems after running the ansible playbook? No. For example, the above mentioned package installed as expected. We didn't do much with the laptops after installing them, though.

I noticed that problem when I checked out this rails app I created for testing purposes: https://github.com/phillipoertel/rails-dummy. It is completely nonfunctional (only the generated stuff) but has a dependency to the pg gem, since we're gonna need that for the course. bundle failed on all four of the laptops we tried (all of them some Dells, I think Inspiron E6410 and E6510). After installing libpq-dev, bundle finished successfully.

I'm surprised you didn't get that problem, btw.

**Comment by Javachic** [comment]
Hm, I'd need to check with the dev who ran the scripts (one of our students, from Afghanistan) on the donated devices. I know there was some fiddling after-the-fact on some devices, but since we didn't cover generating a rails app during pilot week, the pq gem issue likely wasn't identified. I _think_ we're going to be working with a batch of IBM ThinkPads soon. For these laptops, do you recommend running the Ansible playbook > installing libpq-dev > test-generating a new rails app?

**Comment by phillipoertel** [comment]
While I'm not a Linux/Ubuntu expert, I don't think our error had something to do with the hardware. I'd expect you to have the same problems on your machines, since you're using the same Ubuntu and apt packages for Ruby and PostgreSQL.

> For these laptops, do you recommend running the Ansible playbook > installing libpq-dev > test-generating a new rails app?
- @sangyye already added the libpq-dev to the playbook, so you don't need to install libpq-dev manually.
- generating a Rails app is a nice smoke test you could do to check Ruby and Rails were installed correctly. 
- for a more difficult test, check out the above repository and bundle. If that works, add eventmachine and nokogiri to the Gemfile and bundle again. If that works, you got some of the most troublesome gems to compile properly :-)

**Comment by sangyye** [comment]
Btw, I build the script that you can rerun it as much as you want, It will only change and add things that are not already there. So bringing computers on the latest release is no problem.

**Comment by phillipoertel** [comment]
:+1:

**Comment by Javachic** [comment]
Ah, great! Thanks for the clarification - I see the notes, etc. from the last commit now :-)

**Comment by phillipoertel** [comment]
I just tried installing some more troublesome gems on one of our laptops (libv8, eventmachine, nokogiri, puma) and had no issues at all :-)

**Comment by Javachic** [comment]
ah, excellent. good for us to know :-)

**Comment by Javachic** [comment]
Hi Christian - we are currently running the install script and wondering how long it usually takes (if all goes well)?

**Comment by phillipoertel** [comment]
It depends on the machine (how many extra packages have to be downloaded) and it's speed. In our session, setting up Ubuntu took 10-15 minutes, the Rails stuff another 10-15.

**Comment by Javachic** [comment]
Thanks! We had few problems so far and 10-15 mins was about how long it took :-)
