### ISSUE TITLE
Script failed on installing atom

### ISSUE THREAD

**Issue by pihme** [RefugeesOnRails/machina#5]
Executing the script it failed at installing atom. I installed it manually. Not sure whether I missed some stuff from the script after atom, though.

Error message below:

`TASK [download atom editor] ****************************************************
changed: [localhost]

TASK [install atom editor] *****************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to install package: E:Could not open file /home//atom-amd64.deb - open (2: No such file or directory), E:Unable to determine file size for fd -1 - fstat (9: Bad file descriptor), E:Read error - read (9: Bad file descriptor)"}

PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=10   unreachable=0    failed=1 `

**Comment by sangyye** [comment]
Looks like a problem with the username detection, maybe ansible 2.0 does things differently, I'm on it.

**Comment by sangyye** [comment]
This should fix it, but it works only with the latest version of ansible. But the install script should get the latest, so this is no Problem.

**Comment by pihme** [comment]
no changes; ansible version at my machine is 2.0.0.2

**Comment by pihme** [comment]
I removed the atom task to run the rest of the script. The rest of the script went smoothly.

**Comment by sangyye** [comment]
@pihme I can't reproduce your error. The thing I was fixing was the setting of the local_user that I thought was the problem here. I need more infos to understand the problem.
- Do you use Ubuntu 14.04?
- Are you executing the playbook/script as normal user or root?
- How do you execute the playbook? Do you use the `install-machina.sh`? I have to say that using the shell script as normal user is the recommend way to install.
- Do you call the playbook as normal user with this command `ansible-playbook -i "localhost," -c local site.yml --ask-sudo-pass`?

**Comment by pihme** [comment]
I also cannot reproduce it either. On the original machine, where I installed atom manually it now says that a later version is already installed. It's likely that it also said that yesterday, and I didn't pay attention. 
I reran the script on a clean machine and had no problems.
So sorry for the inconvenience.

**Comment by sangyye** [comment]
No worries, good thing the problem is solved now, the worst would been to have a problem that I can't reproduce :smile:
